Repository phalcon/migrations, pull requests merged in 2020-03, with the labels that each got.

#64 #12 - Phalcon migrations phar
  box.json
  composer.json
  composer.lock
Labels: enhancement

#67 #12 - Implement release-phar.yml
  .github/workflows/release-phar.yml
Labels: enhancement

#56 Refactor Model Migration
  src/Migration/Action/Generate.php
  src/Mvc/Model/Migration.php
  src/Utils.php
  tests/Integration/Migration/Action/GenerateTest.php
  tests/Unit/Migration/Action/GenerateTest.php
Labels: MySQL, PostgreSQL, SQLite, enhancement

#69 #66 - Fixed running missed in between migrations
  src/Migrations.php
  tests/Integration/MigrationsTest.php
  tests/var/issues/66/0.0.1/issue66.php
  tests/var/issues/66/0.0.2/issue66.php
  tests/var/issues/66/0.0.3/issue66.php
  tests/var/issues/66/0.0.4/issue66.php
Labels: MySQL, PostgreSQL, SQLite, bug

#73 Remove extended classes of Phalcon PDO and Dialect
  src/Db/Adapter/Pdo/PdoPostgresql.php
  src/Db/Dialect/DialectMysql.php
  src/Db/Dialect/DialectPostgresql.php
  src/Migrations.php
  src/Mvc/Model/Migration.php
  tests/unit/Db/Adapter/Pdo/PdoPostgresqlTest.php
  tests/unit/Db/Dialect/DialectMysqlTest.php
  tests/unit/Db/Dialect/DialectPostgresqlTest.php
Labels: MySQL, PostgreSQL

#74 #68 - Added new option to ignore referenced schema
  psalm.xml.dist
  src/Console/Commands/Migration.php
  src/Migration/Action/Generate.php
  src/Migrations.php
  src/Mvc/Model/Migration.php
  tests/cli/GenerateCest.php
  tests/integration/Migration/Action/GenerateCest.php
Labels: MySQL, NFR, PostgreSQL, enhancement

#75 #11 - Added new option to skip foreign checks
  phalcon-migrations
  src/Console/Color.php
  src/Console/Commands/Migration.php
  src/Migration/Action/Generate.php
  src/Migrations.php
  src/Mvc/Model/Migration.php
  src/Version/IncrementalItem.php
  tests/_support/Helper/Mysql.php
  tests/cli/GenerateCest.php
  tests/cli/RunCest.php
  tests/integration/Migration/Action/GenerateCest.php
  tests/mysql.suite.yml
Labels: MySQL, NFR, bug

#77 Removing Column::TYPE_DECIMAL from noSizeColumnType
  src/Migration/Action/Generate.php
  tests/mysql/ColumnTypesCest.php
Labels: MySQL, bug

#81 #80 - Added possibility to pass some options via config
  composer.lock
  src/Console/Commands/Migration.php
  tests/cli/RunCest.php
  tests/mysql.suite.yml
Labels: bug, enhancement

#86 Improve tests codebase
  CHANGELOG.md
  phpstan.neon.dist
  src/Generator/Snippet.php
  src/Migration/Action/Generate.php
  src/Mvc/Model/Migration.php
  src/Options/OptionsAware.php
  src/Utils.php
  tests/integration/Migration/Action/GenerateCest.php
Labels: enhancement, tests
